language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install: npm install
before_script: echo 'Running unit tests'
script: npm test
before_deploy: echo 'All unit tests passed; Preparing to deploy to AWS'
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-development
  on:
    branch: development
after_deploy: echo 'Successfully Trigger Docker Hub build'
env:
  global:
  - secure: LJNyqMr2+QN2qoZUS67iG8MieNkQeQekd0JLUSt0/Ve9tr+K/OPDB2bwW2zD30em5SwQ+h6hSZYNBAyH3l5G9XRH4dizG9s6BpURb9Ng6TvW+ebFSKtGyOHNUCaL7LAIcnckYCqG77anjjuzeGlZuTrLB9fCpOEBS5+wHhmXyOJf5pt8FIS2cRwM6FFCovZUCyZAFn59V15QaO1Liw8jYi4CGNwUFga5yvG3ZNRPNmA0pLJkGNqBDpXMzHwTbqNGWoOCInWEQ3NUIJ0iH0GhxFtn6HqKPlCgdZPWNanSSr+QMRh01FVYA7nnyKVkfMHBDqNw5iUWlKA8s0FuKPgdPgvFy8Ku/YwUXLncpdpJ59ht8fhj7d2A84kZqPAsJue2szYLMgJvzaiGDcItvamhZfZL0EnVVcdnWISK792jU18gAyE0pg3ZA6hcl90KGdyE7XDqycosce4YspRf7b7LAesNfeg/WPZ7Pdx9vDAD1J94e7rXaO8akFdS5f5MpcHEy1HhYlFyTbRvAPx9uGkypypOoQqqUDxT25LyhnWV2+bwdTqxKXxkyP/PvJ2eTsAT7fnUxrC2igeejn70BfpMxy24qYt6cAQJT0PpCXTWJopGuKU9oKjhfE7RolMB6bEZpruDZ8mKnawlLirYy3xNRnebbPbs2tD9NHroOvl5qIQ=
